### PR TITLE
Non production add ruby 2 7 support

### PR DESCRIPTION
**Pull request by jebentier**

### CODE REVIEW

**Review by yinonrousso — APPROVED** [review]
Nice 💯

**Review by gwynethallwright — APPROVED** [review]

**Review by dcaddell — APPROVED** [review]
I know that this isn't technically changing functionality in the gem, but this is officially dropping Rails 4 support. It seems like this should be associated with a release since the gem is public.

Approving because I don't feel super strongly about this but think it's worth discussion.

**Review by robertp — APPROVED** [review]
LGTM! (I agree with Drew re: removing rails 4 support)

**Comment by jebentier** [comment]
I've gone ahead and added the notes to the changelog, but since this required no functional changes, there no need for a new release of the gem for these. So they will be packaged with the next necessary release of the gem.

**Pull request merged**
